### ISSUE TITLE
Style question - 8Bit or modern?

### ISSUE THREAD

**Issue by ghost** [eclancy68/FirstFizz#16]
Should our sounds, music, and art style aim for an 8 bit theme? This makes sounds easier (we can use SFXR to make them all) 

Or do we want to use free music/sounds, aim for a modern art style?

We could also use a modern art style, and use 8bit sounds.

**Comment by ghost** [comment]
I like the idea of using SFXR for sounds, so we can make them ourselves. Music I don't care as much about.

**Comment by ghost** [comment]
Also, modern art would be easier for me, but I can learn 8bit art if you'd like to learn that.

**Comment by Rhystus** [comment]
I'm game for doing free music for now. I'd like to do original music on the next one, or this one if we want to further this one more.

**Comment by Rhystus** [comment]
I'm game for doing free music for now. I'd like to do original music on the next one, or this one if we want to further this one more.

**Comment by Rhystus** [comment]
I'll give this more thought in terms of art. I think 8 bit could be easier for us to produce, since I'm not incredibly artistic, but modern art is, well, modern. I'll come back to this one.

**Comment by Rhystus** [comment]
As discussed, we'll do some modern art and see what your friend comes up with. Sounds like a solid plan! We'll have a meeting with her to discuss more details.
